<?php
echo "Olá mundo";
echo "Tetste olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";