<?php
echo "Olá mundo";
echo "Teste olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";
echo "Olá mundo";